apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-qvk8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-qvk8@sha256:98334cbb766e0f21c237edb515902e8b619dceafaa99bbd0443365bc9bda379e
        name: my-python
        resources: {}
status: {}
